"""Dress BP_Godfrey_Performer in the Victorian Gentleman FBX costume via IK Retarget
(MetaHuman Body -> Genesis 8 costume).

Creates:
  /Game/MetaHumans/Costume/Retargeting/IK_Victorian_Genesis8
  /Game/MetaHumans/Costume/Retargeting/RTG_MetaHuman_To_Victorian

Wires Costume skeletal mesh on BP_Godfrey_Performer, hides MHC default outfits,
assigns UGodfreyCostumeRetargetAnimInstance.

Headless (forward slashes required):
  UnrealEditor-Cmd.exe "D:/UE Projects/MetaHuman_Baseline_UE58_Test/UnrealPerformer.uproject"
    -ExecutePythonScript="D:/UE Projects/MetaHuman_Baseline_UE58_Test/Scripts/dress_victorian_costume_on_godfrey.py"
    -unattended -nop4 -nosplash -log
"""
from __future__ import annotations

import os
import sys
import time

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPT_DIR not in sys.path:
    sys.path.insert(0, SCRIPT_DIR)

import unreal

import importlib
import godfrey_blueprint_wiring as wiring  # noqa: E402

importlib.reload(wiring)

COSTUME_MESH = "/Game/MetaHumans/Costume/Victorian_Gentleman"
COSTUME_PHYS = "/Game/MetaHumans/Costume/Victorian_Gentleman_PhysicsAsset"
MH_BODY_PREVIEW = "/Game/MetaHumans/MHC_Errol/Body/SKM_MHC_CaptainGodfrey_BodyMesh"
RETARGET_DIR = "/Game/MetaHumans/Costume/Retargeting"
# Source IK must be built from the *actual* Body mesh (not stock m_med_nrw preview).
MH_BODY_IK = f"{RETARGET_DIR}/IK_CaptainGodfrey_Body"
VICTORIAN_IK = f"{RETARGET_DIR}/IK_Victorian_Genesis8"
RETARGETER = f"{RETARGET_DIR}/RTG_MetaHuman_To_Victorian"
COSTUME_COMPONENT = "VictorianCostume"
COSTUME_ANIM_CLASS = "/Script/UnrealPerformer.GodfreyCostumeRetargetAnimInstance"
MHC_OUTFIT_LABELS = ("SkeletalMesh", "SkeletalMesh1", "SkeletalMesh2")

REPORT = "DressVictorianCostumeOnGodfrey.txt"
_lines: list[str] = []


def log(msg: str) -> None:
    _lines.append(msg)
    unreal.log(f"[DressVictorian] {msg}")


def write_report(ok: bool) -> None:
    path = unreal.Paths.convert_relative_path_to_full(
        unreal.Paths.project_saved_dir() + REPORT
    )
    if "MetaHuman_Baseline" not in path.replace("\\", "/"):
        path = r"D:/UE Projects/MetaHuman_Baseline_UE58_Test/Saved/" + REPORT
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(("RESULT: PASS\n" if ok else "RESULT: FAIL\n") + "\n".join(_lines) + "\n")
    log(f"Report: {path}")


def ensure_dir(path: str) -> None:
    if not unreal.EditorAssetLibrary.does_directory_exist(path):
        unreal.EditorAssetLibrary.make_directory(path)


def wait_asset_registry() -> None:
    registry = unreal.AssetRegistryHelpers.get_asset_registry()
    if hasattr(registry, "search_all_assets"):
        registry.search_all_assets(True)
    for _ in range(80):
        try:
            if not registry.is_loading_assets():
                break
        except Exception:
            break
        time.sleep(0.25)


def _clear_retarget_chains(controller) -> None:
    try:
        chains = list(controller.get_retarget_chains())
    except Exception:
        return
    for chain in chains:
        name = None
        for attr in ("chain_name", "ChainName", "name", "Name"):
            try:
                name = getattr(chain, attr)
                if name:
                    break
            except Exception:
                continue
        if not name:
            continue
        try:
            controller.remove_retarget_chain(name)
        except Exception:
            try:
                controller.remove_retarget_chain(unreal.Name(str(name)))
            except Exception:
                pass


def ensure_ik_rig(
    asset_path: str,
    asset_name: str,
    preview_mesh: unreal.SkeletalMesh,
    fallback_chains: tuple[tuple[str, str, str], ...] | None = None,
    retarget_root: str | None = None,
) -> unreal.IKRigDefinition:
    ensure_dir(RETARGET_DIR)

    if unreal.EditorAssetLibrary.does_asset_exist(asset_path):
        ik = unreal.load_asset(asset_path)
        log(f"Refreshing {asset_path}")
    else:
        factory = unreal.IKRigDefinitionFactory()
        ik = unreal.AssetToolsHelpers.get_asset_tools().create_asset(
            asset_name, RETARGET_DIR, unreal.IKRigDefinition, factory
        )
        if not ik:
            raise RuntimeError(f"Failed to create {asset_path}")
        log(f"Created {asset_path}")

    controller = unreal.IKRigController.get_controller(ik)
    controller.set_skeletal_mesh(preview_mesh)
    _clear_retarget_chains(controller)

    auto_ok = False
    try:
        auto_ok = bool(controller.apply_auto_generated_retarget_definition())
        log(f"{asset_name} ApplyAutoGeneratedRetargetDefinition -> {auto_ok}")
    except Exception as exc:
        log(f"WARN: {asset_name} auto retarget definition: {exc}")

    if not auto_ok and fallback_chains:
        none = unreal.Name("None")
        for chain_name, start_bone, end_bone in fallback_chains:
            try:
                created = controller.add_retarget_chain(
                    unreal.Name(chain_name),
                    unreal.Name(start_bone),
                    unreal.Name(end_bone),
                    none,
                )
                log(f"IK chain {created} <- {start_bone}..{end_bone}")
            except Exception as exc:
                log(f"WARN: chain {chain_name}: {exc}")
        if retarget_root:
            try:
                controller.set_retarget_root(unreal.Name(retarget_root))
            except Exception as exc:
                log(f"WARN: set_retarget_root: {exc}")

    unreal.EditorAssetLibrary.save_loaded_asset(ik)
    return ik


def ensure_body_ik(preview_mesh: unreal.SkeletalMesh) -> unreal.IKRigDefinition:
    # MetaHuman / MHC body bone names
    fallback = (
        ("Root", "root", "root"),
        ("Spine", "spine_01", "spine_05"),
        ("Head", "neck_01", "head"),
        ("LeftClavicle", "clavicle_l", "clavicle_l"),
        ("RightClavicle", "clavicle_r", "clavicle_r"),
        ("LeftArm", "upperarm_l", "hand_l"),
        ("RightArm", "upperarm_r", "hand_r"),
        ("LeftLeg", "thigh_l", "foot_l"),
        ("RightLeg", "thigh_r", "foot_r"),
    )
    return ensure_ik_rig(MH_BODY_IK, "IK_CaptainGodfrey_Body", preview_mesh, fallback, "pelvis")


def ensure_victorian_ik(preview_mesh: unreal.SkeletalMesh) -> unreal.IKRigDefinition:
    fallback = (
        ("Root", "hip", "hip"),
        ("Spine", "abdomenLower", "chestUpper"),
        ("Head", "neckLower", "head"),
        ("LeftClavicle", "lCollar", "lCollar"),
        ("RightClavicle", "rCollar", "rCollar"),
        ("LeftArm", "lShldrBend", "lHand"),
        ("RightArm", "rShldrBend", "rHand"),
        ("LeftLeg", "lThighBend", "lFoot"),
        ("RightLeg", "rThighBend", "rFoot"),
    )
    return ensure_ik_rig(VICTORIAN_IK, "IK_Victorian_Genesis8", preview_mesh, fallback, "hip")


def ensure_retargeter(
    source_ik: unreal.IKRigDefinition,
    target_ik: unreal.IKRigDefinition,
    source_mesh: unreal.SkeletalMesh,
    target_mesh: unreal.SkeletalMesh,
) -> unreal.IKRetargeter:
    if unreal.EditorAssetLibrary.does_asset_exist(RETARGETER):
        rtg = unreal.load_asset(RETARGETER)
        log(f"Refreshing existing {RETARGETER}")
    else:
        ensure_dir(RETARGET_DIR)
        factory = unreal.IKRetargetFactory()
        rtg = unreal.AssetToolsHelpers.get_asset_tools().create_asset(
            "RTG_MetaHuman_To_Victorian",
            RETARGET_DIR,
            unreal.IKRetargeter,
            factory,
        )
        if not rtg:
            raise RuntimeError("Failed to create RTG_MetaHuman_To_Victorian")
        log(f"Created {RETARGETER}")

    controller = unreal.IKRetargeterController.get_controller(rtg)

    try:
        num_ops = int(controller.get_num_retarget_ops())
    except Exception:
        num_ops = 0
    log(f"RTG ops before setup: {num_ops}")
    if num_ops <= 0:
        try:
            controller.add_default_ops()
            log(f"add_default_ops -> {controller.get_num_retarget_ops()}")
        except Exception as exc:
            log(f"WARN add_default_ops: {exc}")

    controller.set_ik_rig(unreal.RetargetSourceOrTarget.SOURCE, source_ik)
    controller.set_ik_rig(unreal.RetargetSourceOrTarget.TARGET, target_ik)
    try:
        controller.set_preview_mesh(unreal.RetargetSourceOrTarget.SOURCE, source_mesh)
        controller.set_preview_mesh(unreal.RetargetSourceOrTarget.TARGET, target_mesh)
    except Exception as exc:
        log(f"WARN: set_preview_mesh: {exc}")

    try:
        controller.clean_chain_maps()
    except Exception as exc:
        log(f"WARN clean_chain_maps: {exc}")

    try:
        controller.auto_map_chains(unreal.AutoMapChainType.FUZZY, True)
        log("auto_map_chains FUZZY OK")
    except Exception as exc:
        log(f"WARN: auto_map_chains: {exc}")

    # UE 5.8: maps live on retarget ops via set_source_chain(source, target).
    mapped = 0
    target_ik_ctrl = unreal.IKRigController.get_controller(target_ik)
    source_ik_ctrl = unreal.IKRigController.get_controller(source_ik)
    try:
        source_names = {
            str(c.get_editor_property("chain_name"))
            for c in source_ik_ctrl.get_retarget_chains()
        }
    except Exception:
        source_names = set()
    try:
        target_chains = list(target_ik_ctrl.get_retarget_chains())
    except Exception:
        target_chains = []
    for chain in target_chains:
        try:
            name = str(chain.get_editor_property("chain_name"))
        except Exception:
            continue
        if name not in source_names:
            continue
        try:
            controller.set_source_chain(unreal.Name(name), unreal.Name(name))
            src = str(controller.get_source_chain(unreal.Name(name)))
            if src and src != "None":
                mapped += 1
                log(f"mapped {name} <= {src}")
        except Exception as exc:
            log(f"WARN: set_source_chain {name}: {exc}")
    log(f"Explicit chain maps set: {mapped}")

    unreal.EditorAssetLibrary.save_loaded_asset(rtg)
    return rtg


def hide_mhc_outfits(bp) -> list[str]:
    hidden: list[str] = []
    for label in MHC_OUTFIT_LABELS:
        comp, _ = wiring.find_component(bp, label)
        if not comp:
            continue
        if wiring.set_prop(comp, ["b_hidden_in_game", "bHiddenInGame"], True):
            hidden.append(label)
        wiring.set_prop(comp, ["visible", "bVisible"], False)
    return hidden


def _add_costume_skeletal_mesh_component(bp) -> object:
    existing, _ = wiring.find_component(bp, COSTUME_COMPONENT)
    if existing:
        return existing

    component_class = unreal.load_class(None, "/Script/Engine.SkeletalMeshComponent")
    if not component_class:
        raise RuntimeError("Could not load SkeletalMeshComponent class")

    subsystem = unreal.get_engine_subsystem(unreal.SubobjectDataSubsystem)
    if not subsystem:
        raise RuntimeError("SubobjectDataSubsystem unavailable")

    actor_handle, root_handle = wiring.find_subobject_handles(bp)
    lib = unreal.SubobjectDataBlueprintFunctionLibrary
    body_handle = None
    for handle in subsystem.k2_gather_subobject_data_for_blueprint(bp):
        data = lib.get_data(handle)
        if not data or not lib.is_component(data):
            continue
        if str(lib.get_variable_name(data)) == "Body":
            body_handle = handle
            break

    parent_handle = body_handle or root_handle or actor_handle
    if not parent_handle:
        raise RuntimeError("No parent handle for VictorianCostume")

    params = unreal.AddNewSubobjectParams()
    for prop, value in (
        ("ParentHandle", parent_handle),
        ("parent_handle", parent_handle),
        ("NewClass", component_class),
        ("new_class", component_class),
        ("BlueprintContext", bp),
        ("blueprint_context", bp),
    ):
        try:
            params.set_editor_property(prop, value)
        except Exception:
            pass

    try:
        add_result = subsystem.add_new_subobject(params)
    except TypeError:
        fail_reason = unreal.Text()
        add_result = subsystem.add_new_subobject(params, fail_reason)

    new_handle = add_result[0] if isinstance(add_result, (tuple, list)) else add_result
    if not new_handle:
        raise RuntimeError("add_new_subobject failed for VictorianCostume")

    # UE 5.8 Python: rename_subobject expects SubobjectDataHandle, not a sequence.
    renamed = False
    last_rename_err = None
    for rename_args in (
        (new_handle, unreal.Text(COSTUME_COMPONENT)),
        (new_handle, COSTUME_COMPONENT),
    ):
        try:
            subsystem.rename_subobject(*rename_args)
            renamed = True
            break
        except Exception as exc:
            last_rename_err = exc
    if not renamed:
        log(f"WARN: rename_subobject: {last_rename_err}")

    unreal.BlueprintEditorLibrary.compile_blueprint(bp)

    costume, label = wiring.find_component(bp, COSTUME_COMPONENT)
    if costume:
        log(f"Added component label={label}")
        return costume

    known = {"Body", "Face", *MHC_OUTFIT_LABELS}
    skip_tokens = ("Hair", "Beard", "Eyebrow", "Eyelash", "Mustache", "Fuzz", "Groom")
    candidates = []
    for label, component, _h, _d in wiring.iter_all_components(bp):
        cls = component.get_class().get_name()
        if "SkeletalMeshComponent" not in cls:
            continue
        if label in known or any(tok in label for tok in skip_tokens):
            continue
        candidates.append(label)
        # Prefer names that look like auto-added skeletal meshes.
        if label.startswith("SkeletalMesh") or "Costume" in label or "Victorian" in label:
            log(f"Using newly added skeletal mesh as costume: {label}")
            return component

    if candidates:
        label = candidates[-1]
        costume, _ = wiring.find_component(bp, label)
        if costume:
            log(f"Using fallback costume component: {label}")
            return costume

    raise RuntimeError(
        f"VictorianCostume component not found after add (candidates={candidates})"
    )


def ensure_costume_component(bp) -> object:
    mesh = unreal.load_asset(COSTUME_MESH)
    if not mesh:
        raise RuntimeError(f"Missing costume mesh {COSTUME_MESH}")

    anim_class = unreal.load_class(None, COSTUME_ANIM_CLASS)
    if not anim_class:
        raise RuntimeError(
            f"Missing {COSTUME_ANIM_CLASS} — rebuild UnrealPerformer C++ (IKRig + costume anim instance)."
        )

    body, _ = wiring.find_component(bp, "Body")
    if not body:
        raise RuntimeError("Body component missing on performer")

    costume = _add_costume_skeletal_mesh_component(bp)

    costume.set_editor_property("skeletal_mesh", mesh)
    try:
        costume.set_editor_property("SkinnedAsset", mesh)
    except Exception:
        pass
    wiring.set_prop(costume, ["anim_class", "AnimClass"], anim_class)

    phys = unreal.load_asset(COSTUME_PHYS)
    if phys:
        try:
            costume.set_editor_property("physics_asset_override", phys)
        except Exception:
            wiring.set_prop(costume, ["physics_asset_override", "PhysicsAssetOverride"], phys)

    wiring.set_prop(costume, ["b_hidden_in_game", "bHiddenInGame"], False)
    wiring.set_prop(costume, ["visible", "bVisible"], True)
    wiring.set_prop(
        costume,
        ["visibility_based_anim_tick_option", "VisibilityBasedAnimTickOption"],
        unreal.VisibilityBasedAnimTickOption.ALWAYS_TICK_POSE_AND_REFRESH_BONES,
    )
    wiring.set_prop(
        body,
        ["visibility_based_anim_tick_option", "VisibilityBasedAnimTickOption"],
        unreal.VisibilityBasedAnimTickOption.ALWAYS_TICK_POSE_AND_REFRESH_BONES,
    )
    return costume


def main() -> None:
    log("=== Dress Victorian costume on BP_Godfrey_Performer ===")
    project_dir = unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_dir())
    log(f"Project: {project_dir}")
    if "MetaHuman_Baseline_UE58_Test" not in project_dir.replace("\\", "/"):
        raise RuntimeError("Project did not load — use quoted forward-slash .uproject path")

    wait_asset_registry()

    costume_mesh = unreal.load_asset(COSTUME_MESH)
    mh_body = unreal.load_asset(MH_BODY_PREVIEW)
    if not costume_mesh or not mh_body:
        raise RuntimeError(
            f"Missing assets costume={bool(costume_mesh)} mh_body={bool(mh_body)}"
        )

    body_ik = ensure_body_ik(mh_body)
    victorian_ik = ensure_victorian_ik(costume_mesh)
    ensure_retargeter(body_ik, victorian_ik, mh_body, costume_mesh)

    bp = unreal.load_asset(wiring.GODFREY_PERFORMER_BP)
    if not bp:
        raise RuntimeError(f"Missing {wiring.GODFREY_PERFORMER_BP}")

    hidden = hide_mhc_outfits(bp)
    log(f"Hidden MHC outfits: {hidden}")

    costume = ensure_costume_component(bp)
    log(f"Costume mesh={costume.get_editor_property('skeletal_mesh')}")
    log(f"Costume AnimClass={wiring._anim_class_name(costume)}")

    unreal.BlueprintEditorLibrary.compile_blueprint(bp)
    if not wiring.save_godfrey_performer_blueprint(bp):
        raise RuntimeError(wiring.BP_SAVE_LOCK_HINT)

    for path in (MH_BODY_IK, VICTORIAN_IK, RETARGETER):
        if unreal.EditorAssetLibrary.does_asset_exist(path):
            unreal.EditorAssetLibrary.save_asset(path, only_if_is_dirty=False)

    write_report(True)
    log(
        "PASS — PIE BP_Godfrey_Performer: Victorian costume should follow Body via IK retarget. "
        "Tune RTG_MetaHuman_To_Victorian retarget poses if shoulders/hips look off. "
        "Face/ACE unchanged."
    )


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        unreal.log_error(f"[DressVictorian] {exc}")
        write_report(False)
        sys.exit(1)
